// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysUser = "sys_user"

// SysUser mapped from table <sys_user>
type SysUser struct {
	Id              int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:编码" json:"id"` // 编码
	Mobile          string         `gorm:"column:mobile;comment:用户名" json:"mobile"`                      // 手机号
	Password        string         `gorm:"column:password;comment:密码" json:"password"`                   // 密码
	PasswordVersion int8           `gorm:"column:password_version;comment:密码版本" json:"password_version"` // 密码版本
	NickName        string         `gorm:"column:nick_name;comment:昵称" json:"nick_name"`                 // 昵称
	RoleID          int64          `gorm:"column:role_id;comment:角色ID" json:"role_id"`                   // 角色ID
	Salt            string         `gorm:"column:salt;comment:加盐" json:"salt"`                           // 加盐
	Avatar          string         `gorm:"column:avatar;comment:头像" json:"avatar"`                       // 头像
	Sex             string         `gorm:"column:sex;comment:性别" json:"sex"`                             // 性别
	Email           string         `gorm:"column:email;comment:邮箱" json:"email"`                         // 邮箱
	DeptID          int64          `gorm:"column:dept_id;comment:部门" json:"dept_id"`                     // 部门
	PostID          int64          `gorm:"column:post_id;comment:岗位" json:"post_id"`                     // 岗位
	Remark          string         `gorm:"column:remark;comment:备注" json:"remark"`                       // 备注
	Status          string         `gorm:"column:status;comment:状态" json:"status"`                       // 状态
	CreateBy        int64          `gorm:"column:create_by;comment:创建者" json:"create_by"`                // 创建者
	UpdateBy        int64          `gorm:"column:update_by;comment:更新者" json:"update_by"`                // 更新者
	CreatedAt       time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`             // 创建时间
	UpdatedAt       time.Time      `gorm:"column:updated_at;comment:最后更新时间" json:"updated_at"`           // 最后更新时间
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`             // 删除时间
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
