apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goapp
    env: testing
    lang: golang
  name: goapp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: goapp-config
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          name: goapp
          ports:
            - containerPort: 9990
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          startupProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 9990
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

